### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by sqs** [coreos/go-etcd#163]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with go-etcd. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable go-etcd on @Sourcegraph by going to https://sourcegraph.com/github.com/coreos/go-etcd and clicking on Settings? (It should only take 15 seconds.)

Thank you!

Here are some screenshots to show off what it looks like...

![image](https://cloud.githubusercontent.com/assets/1976/4633888/3c4d6cfa-53cb-11e4-8d33-9f957c04cf7e.png)
https://sourcegraph.com/github.com/coreos/go-etcd/.pulls/156/defs
![image](https://cloud.githubusercontent.com/assets/1976/4633905/5bf53b8c-53cb-11e4-988b-38ac4a33e13f.png)
https://sourcegraph.com/github.com/coreos/go-etcd@master/.GoPackage/github.com/coreos/go-etcd/etcd/.def/NewClientFromFile

**Comment by philips** [comment]
It is difficult for us to manage the OAUTH access levels to give sourcegraph what it needs. If GitHub and Sourcegraph work together to make it easier for us we will enable it but until that happens I won't be enabling sourcegraph. Thank you.
