### ISSUE TITLE
Client.SetDir() returns "102: Not a file" if directory already exists

### ISSUE THREAD

**Issue by MStrenge** [coreos/go-etcd#168]
Hi,

when calling SetDir() to create a directory with TTL or update TTL, the function returns "102: Not a file" if the directory is already existing. Is it supposed to work?

I tested with latest go-etcd and etcd 0.3 to 0.5a.

BR,
Martin

**Comment by xiang90** [comment]
Yes. You can only replace (set = create or replace) a file, but not a dir. Dir can only be created/deleted/updated.
