### ISSUE TITLE
wait returns unexpected end of JSON every 5 minutes

### ISSUE THREAD

**Issue by emicklei** [coreos/go-etcd#170]
In a loop, I watch for changes in a directory
```
p.client.Watch(storesKey, 0, true, nil, nil)
```
All changes are picked up and handled by my app.
However, every 5 minutes I receive an invalid response, which I currently just ignore (skip this event).

```
W1110 11:16:35.776132 49235 etcd_store_dao.go:71] watch failed, skip this event:unexpected end of JSON input
W1110 11:21:35.777721 49235 etcd_store_dao.go:71] watch failed, skip this event:unexpected end of JSON input
W1110 11:26:35.779467 49235 etcd_store_dao.go:71] watch failed, skip this event:unexpected end of JSON input
W1110 11:31:35.779922 49235 etcd_store_dao.go:71] watch failed, skip this event:unexpected end of JSON input
```

Is this really an issue or should this be ignored as I do because it is some hearbeart ping?

**Comment by xiang90** [comment]
@leverly @GeertJohan @emicklei 
etcd 2.0 server will not generate empty json in normal case. The connection will only be closed if the client has actually gone.

#2049
