### ISSUE TITLE
etcdClient.CreateDir() fails with 501: All the given peers are not reachable

### ISSUE THREAD

**Issue by tleyden** [coreos/go-etcd#179]
Steps to reproduce:

* I'm running a 3 node coreos (stable) cluster under vagrant, not sure what the exact build is (how do I find out?)
*  etcd version 0.4.6 
* go-etcd commit b7c233e2ef9be1016c63f66145161b317165ad7e
* Run an ubuntu container
* Inside the container, run the following go code:

```
etcdClient = etcd.NewClient([]string{})
_, err := etcdClient.CreateDir("/couchbase.com/couchbase-node-state", TTL_NONE)
log.Printf("createDir err: %v", err)
```

Here are the errors I'm seeing.  I enabled debug, and added a few log statements of my own:

```
go-etcd2015/01/29 17:32:46 DEBUG: put /couchbase.com/couchbase-node-state, , ttl: 0, [http://127.0.0.1:4001]
go-etcd2015/01/29 17:32:46 DEBUG: Connecting to etcd: attempt 1 for keys/couchbase.com/couchbase-node-state?dir=true&prevExist=false
go-etcd2015/01/29 17:32:46 DEBUG: send.request.to http://127.0.0.1:4001/v2/keys/couchbase.com/couchbase-node-state?dir=true&prevExist=false | method PUT
go-etcd2015/01/29 17:32:46 DEBUG: recv.response.from http://127.0.0.1:4001/v2/keys/couchbase.com/couchbase-node-state?dir=true&prevExist=false
2015/01/29 17:32:46 resp: &{Status:307 Temporary Redirect StatusCode:307 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Location:[http://172.17.8.103:4001/v2/keys/couchbase.com/couchbase-node-state?dir=true&prevExist=false] Date:[Thu, 29 Jan 2015 17:32:46 GMT] Content-Type:[text/plain; charset=utf-8]] Body:0xc2100582c0 ContentLength:-1 TransferEncoding:[chunked] Close:false Trailer:map[] Request:0xc210062410}, status code: 307
2015/01/29 17:32:46 calling checkRetry
2015/01/29 17:32:46 DefaultCheckRetry called, numReqs: 2 err: Unexpected HTTP status code lastResp: {Status:307 Temporary Redirect StatusCode:307 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Location:[http://172.17.8.103:4001/v2/keys/couchbase.com/couchbase-node-state?dir=true&prevExist=false] Date:[Thu, 29 Jan 2015 17:32:46 GMT] Content-Type:[text/plain; charset=utf-8]] Body:0xc2100582c0 ContentLength:-1 TransferEncoding:[chunked] Close:false Trailer:map[] Request:0xc210062410}
2015/01/29 17:32:46 createDir err: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
2015/01/29 17:32:46 Unexpected error: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
2015/01/29 17:32:46 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
exit status 1
```

Under the same environment, I'm able to call `etcdClient.Get()` and everything looks normal.

**Comment by danielbenzvi** [comment]
This error also appeared while using the etcd-backup, which relies on this go-etcd library.
During debugging I noticed that some HTTP methods were changed such as the change from /v2/machines to /v2/members - 0.4.6 returns a 404 to the new method.

This can be seen here: https://github.com/coreos/go-etcd/commit/5348c80bde6223fa53c48ef546b4802db69b1d70#diff-33c1223aac4ef741731cc8c73b4d7777

@xiang90

**Comment by matthiasctx** [comment]
Have the same issue. Reason is that http client does not follow HTTP/1.1 307 Temporary Redirect.
If you connect to http://127.0.0.1:401 (the default) it redirects you to the node ip.
Maybe this can be solved if forcing to use curl channel.

**Comment by brosner** [comment]
I came to the same conclusion in https://github.com/coreos/go-etcd/issues/167#issuecomment-71899508 (for reference)

**Comment by tleyden** [comment]
@brosner ah, that's good to know.  So basically upgrading to etcd 2 will fix the issue?

**Comment by tleyden** [comment]
I can confirm that rolling back to 6aa2da5a7a905609c93036b9307185a04a5a84a5 fixes the issue on CoreOS 522.6.0 (stable)

**Comment by yichengq** [comment]
Hi all, The 5348c80bde6223fa53c48ef546b4802db69b1d70 is written for v2.0 compatibility, so it breaks 0.4.6 client. I have tagged the v0.4.6 tag, and please use that for v0.4.6 etcd cluster.
The current master is for v2.0 etcd cluster.
Thanks for digging and reporting!

**Comment by tleyden** [comment]
ok great.  I think the ticket can be closed then.
