### ISSUE TITLE
Did /v2/machines change to /v2/members ?

### ISSUE THREAD

**Issue by lordelph** [coreos/go-etcd#181]
I was diagnosing [a problem with confd](https://github.com/kelseyhightower/confd/issues/195), where it would not recognize my v0.4.6 etcd cluster. Turns out it was because confd was compiled with the latest etcd client, which was changed to check a node for /v2/members rather then /v2/machines in [this commit](https://github.com/coreos/go-etcd/commit/5348c80bde6223fa53c48ef546b4802db69b1d70#diff-33c1223aac4ef741731cc8c73b4d7777L295)

Is that intentional? Seems like it will cause problems when code using the new client tries to talk to older etcd clusters?

**Comment by yichengq** [comment]
@lordelph Sorry for confusion.
current master is for v2.0 cluster, and i have tagged v0.4.6 for v0.4.6 cluster.

**Comment by lordelph** [comment]
Thanks - I solved my issue by using a prebuilt binary of confd rather than compiling the go source. Will close this ticket now, there's an open ticket on confd for supporting both versions of etcd.
