### ISSUE TITLE
about log

### ISSUE THREAD

**Issue by SandyLing** [coreos/go-etcd#183]
你好，我看了源码发现有打日志
如下：
debug.go:
SetLogger(log.New(ioutil.Discard, "go-etcd", log.LstdFlags))

请问加日志需要自己修改代码吗？

**Comment by xiang90** [comment]
>你好，我看了源码发现有打日志  Hi, I found the following code in the codebase around logging
如下：As following:
debug.go:
SetLogger(log.New(ioutil.Discard, "go-etcd", log.LstdFlags))
请问加日志需要自己修改代码吗？Do I need to change go-etcd to print out the log?

你可以自己更改logger的 SetLogger. You can set your own logger by calling SetLogger.

**Comment by yichengq** [comment]
I think this has been resolved.
