### ISSUE TITLE
Ability to properly close etcd client

### ISSUE THREAD

**Issue by garo** [coreos/go-etcd#187]
As far as I know the etcd client is not goroutine safe so each goroutine should have its own etcd client. Currently there doesn't seem to be any way to properly close a client once its no longer needed.

Example test case: Check the amount of file descriptors under /proc/etcd pid/fd before and during this script is running. You see the amount of descriptors increasing by 100.

```go
package main

import "fmt"
import "github.com/coreos/go-etcd/etcd"
import "time"

func main() {
  for n := 0; n < 100; n++ {
    go func() {
      e := etcd.NewClient([]string{"http://localhost:4001"})
      defer e.CloseCURL()
      e.Get("/", true, false)
    }()
  }

  fmt.Printf("\nClients created\n")
  time.Sleep(1 * time.Minute)
}
```

**Comment by yichengq** [comment]
e.CloseCURL is not used to close idle connections.
i think it is reasonable to support CloseIdleConnections of the underlying transport.
AFAIK, if there is no reference for client, golang will recycle the underlying transport and idle connections. Could you try to wait for some time after all  goroutines exit?

**Comment by garo** [comment]
No, it doesn't seem to garbage collect the idle connections, at least not after 10 minutes. So a proper cleanup routine is needed.

**Comment by yichengq** [comment]
Could you try to hack on this one? I may jump in later.

**Comment by garo** [comment]
I've created this patch which seems to fix the issue, but it might use a bit cleaning up. The trick was to call transport.CloseIdleConnections(), but the transport had to be separately stored in the structure.

The use for CloseCURL() function is a bit weird, should have instead a Close() function where we place this? Is the CloseCURL() even used anywhere?

```diff
diff --git a/etcd/client.go b/etcd/client.go
index 8ecb50e..3d06597 100644
--- a/etcd/client.go
+++ b/etcd/client.go
@@ -5,6 +5,7 @@ import (
        "crypto/x509"
        "encoding/json"
        "errors"
+       "github.com/coreos/etcd/etcdserver/etcdhttp/httptypes"
        "io"
        "io/ioutil"
        "math/rand"
@@ -15,8 +16,6 @@ import (
        "path"
        "strings"
        "time"
-
-       "github.com/coreos/etcd/etcdserver/etcdhttp/httptypes"
 )

 // See SetConsistency for how to use these constants.
@@ -48,6 +47,7 @@ type Client struct {
        config      Config   `json:"config"`
        cluster     *Cluster `json:"cluster"`
        httpClient  *http.Client
+       transport   *http.Transport
        persistence io.Writer
        cURLch      chan string
        // CheckRetry can be used to control the policy for failed requests
@@ -182,6 +182,7 @@ func (c *Client) initHTTPClient() {
                        InsecureSkipVerify: true,
                },
        }
+       c.transport = tr
        c.httpClient = &http.Client{Transport: tr}
 }

@@ -205,6 +206,7 @@ func (c *Client) initHTTPSClient(cert, key string) error {
                TLSClientConfig: tlsConfig,
                Dial:            c.dial,
        }
+       c.transport = tr

        c.httpClient = &http.Client{Transport: tr}
        return nil
@@ -352,6 +354,7 @@ func (c *Client) createHttpPath(serverName string, _path string) string {
 // dial attempts to open a TCP connection to the provided address, explicitly
 // enabling keep-alives with a one-second interval.
 func (c *Client) dial(network, addr string) (net.Conn, error) {
+
        conn, err := net.DialTimeout(network, addr, c.config.DialTimeout)
        if err != nil {
                return nil, err
@@ -379,6 +382,10 @@ func (c *Client) OpenCURL() {
 }

 func (c *Client) CloseCURL() {
+
+       if c.transport != nil {
+               c.transport.CloseIdleConnections()
+       }
        c.cURLch = nil
 }
```

**Comment by yichengq** [comment]
e.CloseCURL is not used to close idle connections. Maybe we need a new API for this.

**Comment by garo** [comment]
Yeah, agree. maybe a Close() function call? I can submit a clean pull request for it if you agree on the general idea on using CloseIdleConnections() and that I store the transport object separately (as seen in the above diff)

**Comment by yichengq** [comment]
Yes, i think that is good. /cc @xiang90

**Comment by ZeissS** [comment]
Solved by https://github.com/coreos/go-etcd/pull/195?

**Comment by yichengq** [comment]
yes
