### ISSUE TITLE
SyncCluster failing on possibly non-existant API endpoint

### ISSUE THREAD

**Issue by buth** [coreos/go-etcd#188]
I've been unable to get the etcd client to properly sync the cluster. From this line in the code:
https://github.com/coreos/go-etcd/blob/master/etcd/client.go#L301

it seems like the `SyncCluster` command is making a call to a `/v2/members` endpoint which, as far as i can tell, does not exist. The result is the client complaining that all the peers are unreachable if the only machine presently listed is not the primary.

**Comment by buth** [comment]
Looks like this is an API difference with the latest version of etcd. Thought that the `v2` prefix would have guaranteed compatibility, but I guess not.

**Comment by yichengq** [comment]
@buth Please use v0.4.6 go-etcd for v0.4 etcd.
