### ISSUE TITLE
SetCluster failing on unmarshalling httptypes.MemberCollection

### ISSUE THREAD

**Issue by ematpl** [coreos/go-etcd#189]
We've noticed that the go-etcd client is failing on Client.SetCluster() when it is pulling in the latest code from https://github.com/coreos/etcd. Adding some debug logging locally reveals the following error when unmarshalling into an `httptypes.MemberCollection` variable:

```
&json.UnmarshalTypeError{Value:"object", Type:(*reflect.rtype)(0x528760)}
```

The issue seems to be [this commit](https://github.com/coreos/etcd/commit/4a77760f56d9ae6ca86a2250aeb3aed0f971a20c), which removed the `UnmarshalJSON` method on `MemberCollection`.

Related issue raised recently on this repo: https://github.com/coreos/go-etcd/issues/188

Thanks,
@ematpl && @atulkc, for the CF Diego team

**Comment by yichengq** [comment]
Thanks for reporting @ematpl and CF Diego team!

**Comment by ematpl** [comment]
Thanks for the fix, @yichengq and @xiang90!
