### ISSUE TITLE
Redirects Not Followed

### ISSUE THREAD

**Issue by BlueDragonX** [coreos/go-etcd#190]
go-etcd does not follow redirects. This ends up surfacing the dreaded "All the given peers are not reachable" error. This was not happening in a previous version as I can roll an older binary of beacon that uses a previous version of go-etcd and it works just fine. Compiling a new version and deploying it will run into this error.

I'm specifically encountering this issue when attempting to talk to the local etcd service which then redirects my to whichever service is primary. go-etcd fails as a result.

**Comment by BlueDragonX** [comment]
It seems the latest commit is the culprit: 6aa2da5a7a905609c93036b9307185a04a5a84a5

**Comment by BlueDragonX** [comment]
I should note that I'm using etcd 0.4.7 in a CoreOS cluster.

**Comment by yichengq** [comment]
Please use tags:v0.4.6 go-etcd for etcd 0.4.7
Current HEAD is for v2.0 etcd
Thanks!
