### ISSUE TITLE
"panic: close of closed channel" under load

### ISSUE THREAD

**Issue by ghodss** [coreos/go-etcd#197]
Hello,

I was running kube-apiserver at a few thousand qps against a single local etcd node (cluster size = 1) on the same server. Between 1 and 20 minutes of running, kube-apiserver crashes with the following panic:

```
panic: close of closed channel
 
goroutine 21939087 [running]:
net/http.func·018()
        /usr/src/go/src/net/http/transport.go:517 +0x2a
net/http.(*Transport).CancelRequest(0xc208089680, 0xc2706df450)
        /usr/src/go/src/net/http/transport.go:284 +0x97
github.com/coreos/go-etcd/etcd.func·003()
        /go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/requests.go:160 +0x236
created by github.com/coreos/go-etcd/etcd.(*Client).SendRequest
        /go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/requests.go:169 +0x3e0
 
goroutine 1 [IO wait]:
net.(*pollDesc).Wait(0xc208831f00, 0x72, 0x0, 0x0)
        /usr/src/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208831f00, 0x0, 0x0)
        /usr/src/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208831ea0, 0x0, 0x7fe6c0edfe08, 0xc2c01f73e8)
        /usr/src/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208184528, 0x582aae, 0x0, 0x0)
        /usr/src/go/src/net/tcpsock_posix.go:234 +0x4e
net/http.tcpKeepAliveListener.Accept(0xc208184528, 0x0, 0x0, 0x0, 0x0)
        /usr/src/go/src/net/http/server.go:1976 +0x4c
net/http.(*Server).Serve(0xc20883c5a0, 0x7fe6c0d288a8, 0xc208184528, 0x0, 0x0)
        /usr/src/go/src/net/http/server.go:1728 +0x92
net/http.(*Server).ListenAndServe(0xc20883c5a0, 0x0, 0x0)
        /usr/src/go/src/net/http/server.go:1718 +0x154
github.com/GoogleCloudPlatform/kubernetes/cmd/kube-apiserver/app.(*APIServer).Run(0xc2080ae840, 0xc20818c000, 0x0, 0xc, 0x0, 0x0)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/cmd/kube-apiserver/app/server.go:391 +0x2363
main.main()
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/cmd/kube-apiserver/apiserver.go:44 +0xd0
 
goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x13884c0)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/golang/glog.init·1
        /go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2a7
[... more logging of thousands more goroutines ...]
```

My uneducated reading of this is that the calling of `c.httpClient.Transport.(*http.Transport).CancelRequest(req)` at https://github.com/coreos/go-etcd/blob/master/etcd/requests.go#L160 potentially more than once is resulting in sometimes reclosing a closed channel. I was maxing out all open ports and connections on the machine so that may have surfaced a race condition that would otherwise happen extremely rarely.

I was playing with increasing `/proc/sys/net/ipv4/ip_local_port_range` and setting `sysctl -w net.ipv4.tcp_tw_reuse=1` on the machine, but I still reproduced the crash with the port_range at normal and tcp_tw_reuse=0.

You can see some notes of tests I was running with the machine at https://gist.github.com/ghodss/db3f2aec931f537669ef.

**Comment by ghodss** [comment]
@yichengq since #108 added the for loop.

**Comment by yichengq** [comment]
Your analysis does make sense. I am asking for golang suggestion and have some easy fix for it. Could you try it(#198) out?

**Comment by ghodss** [comment]
This looks like it would definitely fix the issue, but kubernetes has also made some fixes that now stresses the server much less and makes it harder to hit this race condition. I will close this issue and reopen if I run into it the panic again.

**Comment by xiang90** [comment]
@ghodss We also reported this to golang upstream. It is also solved there: https://github.com/golang/go/issues/10405.

**Comment by ghodss** [comment]
Awesome!
