### ISSUE TITLE
go-etcd may block forever when all machines are down

### ISSUE THREAD

**Issue by yichengq** [coreos/go-etcd#206]
The easy way to reproduce it: `go test -v -run Get` without a etcd cluster running.

from https://github.com/coreos/go-etcd/pull/203#issuecomment-96124576

/cc @ZeaLoVe

**Comment by ZeaLoVe** [comment]
I use the latest API , block forever is gone .
But now I came with something new . Maybe cause by etcd itself .
I test failover case with etcd and skydns. I started 3 etcd machines, and shutdown 2. then SKYDNS got the data out of live time. I try to got these data form etcd by http
then I got these:
{"action":"get","node":{"key":"/skydns/ddd/hd","dir":true,"nodes":[{"key":"/skydns/ddd/hd/n3","value":"{\"host\":\"192.168.181.13\",\"port\":8080,\"priority\":10,\"weight\":100,\"text\":\"for sqlserver\",\"ttl\":30}","expiration":"2015-05-04T09:01:07.237530953Z","ttl":-3,"modifiedIndex":2152561,"createdIndex":2151674},{"key":"/skydns/ddd/hd/n5","value":"{\"host\":\"192.168.181.15\",\"port\":8080,\"priority\":10,\"weight\":100,\"text\":\"for sqlserver\",\"ttl\":30}","expiration":"2015-05-04T09:01:07.058407748Z","ttl":-3,"modifiedIndex":2152562,"createdIndex":2151863},{"key":"/skydns/ddd/hd/n6","value":"{\"host\":\"192.168.181.16\",\"port\":8080,\"priority\":10,\"weight\":100,\"text\":\"for sqlserver\",\"ttl\":30}","expiration":"2015-05-04T09:01:07.059895896Z","ttl":-3,"modifiedIndex":2152563,"createdIndex":2151845},{"key":"/skydns/ddd/hd/n2","value":"{\"host\":\"192.168.181.12\",\"port\":8080,\"priority\":10,\"weight\":100,\"text\":\"for sqlserver\",\"ttl\":30}","expiration":"2015-05-04T09:01:07.060075286Z","ttl":-3,"modifiedIndex":2152565,"createdIndex":2151675},{"key":"/skydns/ddd/hd/n7","value":"{\"host\":\"192.168.181.17\",\"port\":8080,\"priority\":10,\"weight\":100,\"text\":\"for sqlserver\",\"ttl\":30}","expiration":"2015-05-04T09:01:07.237074588Z","ttl":-3,"modifiedIndex":2152560,"createdIndex":2151846},{"key":"/skydns/ddd/hd/n4","value":"{\"host\":\"192.168.181.14\",\"port\":8080,\"priority\":10,\"weight\":100,\"text\":\"for sqlserver\",\"ttl\":30}","expiration":"2015-05-04T09:01:07.059986002Z","ttl":-3,"modifiedIndex":2152564,"createdIndex":2151844}],"modifiedIndex":2102309,"createdIndex":2102309}}

The ttl is negative, but returns to skydns. Is this a bug of etcd?( I adjust my system time of all the etcd machines ,so I think time is not a problem) . In my opinion, etcd in any cases will not return the data out of live time. Even all others down. I hope you can figure it out .thank you!

**Comment by yichengq** [comment]
@ZeaLoVe Maybe. I cannot figure it out because i cannot reproduce it. could you open an issue in etcd if you know more about the case?

**Comment by ZeaLoVe** [comment]
@yichengq  yes, I found it that it was caused by different time setting between etcd machines.Sorry not     reporting this..It solved for days
