### ISSUE TITLE
Panic on SyncCluster

### ISSUE THREAD

**Issue by abronan** [coreos/go-etcd#213]
Using etcd `v2.0.11`, a call to `SyncCluster` provoques a panic. Somehow, it does not happen with older versions of `etcd` like `v0.4.6`.

This is the panic output (apologies for the useless parts):

```
panic: runtime error: index out of range

goroutine 9 [running]:
github.com/coreos/go-etcd/etcd.(*Client).getCancelable(0xc20800a280, 0xc20802bb46, 0x7, 0xc208115320, 0x0, 0xac9b40, 0x0, 0x0)
	/vagrant/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/requests.go:41 +0x4b7
github.com/coreos/go-etcd/etcd.(*Client).get(0xc20800a280, 0xc20802bb46, 0x7, 0xc208115320, 0x4187a1, 0x0, 0x0)
	/vagrant/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/requests.go:62 +0x61
github.com/coreos/go-etcd/etcd.(*Client).RawGet(0xc20800a280, 0xc20802bb46, 0x7, 0x101, 0xc20802bb40, 0x0, 0x0)
	/vagrant/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/get.go:31 +0x26c
github.com/coreos/go-etcd/etcd.(*Client).Get(0xc20800a280, 0xc20802bb46, 0x7, 0x101, 0x300000000000002, 0x0, 0x0)
	/vagrant/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/get.go:11 +0x63
github.com/docker/swarm/pkg/store.(*Etcd).List(0xc20802bae0, 0xc20802bab0, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0)
	/vagrant/src/github.com/docker/swarm/pkg/store/etcd.go:276 +0xbe
github.com/docker/swarm/pkg/store.(*Etcd).WatchTree(0xc20802bae0, 0x7ffea4c81748, 0x5, 0x0, 0x0, 0x0, 0x0)
	/vagrant/src/github.com/docker/swarm/pkg/store/etcd.go:218 +0x12d
github.com/docker/swarm/discovery/kv.func·001()
	/vagrant/src/github.com/docker/swarm/discovery/kv/kv.go:111 +0xe5
created by github.com/docker/swarm/discovery/kv.(*Discovery).Watch
	/vagrant/src/github.com/docker/swarm/discovery/kv/kv.go:125 +0x1b8

goroutine 1 [chan receive]:
github.com/docker/swarm/api.(*Server).ListenAndServe(0xc20803dc20, 0x0, 0x0)
	/vagrant/src/github.com/docker/swarm/api/server.go:117 +0x491
github.com/docker/swarm/cli.manage(0xc2080880c0)
	/vagrant/src/github.com/docker/swarm/cli/manage.go:212 +0xcfa
github.com/codegangsta/cli.Command.Run(0x899570, 0x6, 0x8994d0, 0x1, 0x8cb4d0, 0x17, 0x0, 0x0, 0x0, 0x0, ...)
	/vagrant/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:113 +0x1038
github.com/codegangsta/cli.(*App).Run(0xc2080352b0, 0xc20800a000, 0x8, 0x8, 0x0, 0x0)
	/vagrant/src/github.com/docker/swarm/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:156 +0xcf7
github.com/docker/swarm/cli.Run()
	/vagrant/src/github.com/docker/swarm/cli/cli.go:133 +0x1129
main.main()
	/vagrant/src/github.com/docker/swarm/main.go:13 +0x1b

goroutine 7 [IO wait]:
net.(*pollDesc).Wait(0xc208010840, 0x72, 0x0, 0x0)
	/home/vagrant/.gvm/gos/go1.4/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010840, 0x0, 0x0)
	/home/vagrant/.gvm/gos/go1.4/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2080107e0, 0xc208098000, 0x1000, 0x1000, 0x0, 0x7fcd84681c18, 0xc20802ba00)
	/home/vagrant/.gvm/gos/go1.4/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20802c070, 0xc208098000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/vagrant/.gvm/gos/go1.4/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7fcd84683690, 0xc20802c070, 0xc2080543c8, 0xc208098000, 0x1000, 0x1000, 0x7ad7a0, 0x0, 0x0)
	/home/vagrant/.gvm/gos/go1.4/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc20801ebe0, 0xc208098000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc2080525a0)
	/home/vagrant/.gvm/gos/go1.4/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc2080525a0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/vagrant/.gvm/gos/go1.4/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc208054370)
	/home/vagrant/.gvm/gos/go1.4/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/home/vagrant/.gvm/gos/go1.4/src/net/http/transport.go:660 +0xc9f

goroutine 8 [select]:
net/http.(*persistConn).writeLoop(0xc208054370)
	/home/vagrant/.gvm/gos/go1.4/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/home/vagrant/.gvm/gos/go1.4/src/net/http/transport.go:661 +0xcbc

goroutine 10 [runnable]:
github.com/docker/swarm/cluster/swarm.(*Cluster).monitorDiscovery(0xc208052300, 0xc208052360, 0xc208052540)
	/vagrant/src/github.com/docker/swarm/cluster/swarm/cluster.go:214
created by github.com/docker/swarm/cluster/swarm.NewCluster
	/vagrant/src/github.com/docker/swarm/cluster/swarm/cluster.go:55 +0x436

goroutine 11 [runnable]:
github.com/docker/swarm/cli.func·004()
	/vagrant/src/github.com/docker/swarm/cli/manage.go:110
created by github.com/docker/swarm/cli.setupLeaderElection
	/vagrant/src/github.com/docker/swarm/cli/manage.go:122 +0x758

goroutine 12 [runnable]:
github.com/docker/swarm/cli.func·005()
	/vagrant/src/github.com/docker/swarm/cli/manage.go:124
created by github.com/docker/swarm/cli.setupLeaderElection
	/vagrant/src/github.com/docker/swarm/cli/manage.go:135 +0x7ff

goroutine 13 [runnable]:
github.com/docker/swarm/api.func·008()
	/vagrant/src/github.com/docker/swarm/api/server.go:87
created by github.com/docker/swarm/api.(*Server).ListenAndServe
	/vagrant/src/github.com/docker/swarm/api/server.go:113 +0x412
```

Just wondering but can it be related to the setup part with `--listen-client-urls` and `--advertise-client-urls`? In any case I would expect `SyncCluster` to have no effect if something goes wrong.

**Comment by abronan** [comment]
related to docker/swarm#721

**Comment by yichengq** [comment]
@abronan It can be related to the setting of `--listen-client-urls` and `--advertise-client-urls`, and go-etcd should take care of this case. What is the value of these urls in your case? Any reliable way to reproduce the problem?

**Comment by abronan** [comment]
@yichengq Thanks for the quick answer!

I'm launching an instance on one VM with:

```
$ ./etcd --listen-client-urls 'http://0.0.0.0:2379,http://0.0.0.0:4001' --advertise-client-urls 'http://192.168.42.10:2379,http://192.168.42.10:4001'
```

I'm initializing the etcd client with `http://192.168.42.10:4001`, everything works fine (Set/Get/etc.), just the `SyncCluster` panicking.

I was using this exact same config with etcd `v0.4.6` and this was working fine (although I don't know if the refresh occurred successfully).

An easy way to reproduce would be to launch a local etcd instance (`v2.0.11`) with:

```
$ ./etcd --listen-client-urls 'http://0.0.0.0:2379,http://0.0.0.0:4001' --advertise-client-urls 'http://localhost:2379,http://localhost:4001'
```

And then run the following snippet:

```
package main

import (
	"log"

	"github.com/coreos/go-etcd/etcd"
)

func main() {
	entries := []string{"http://localhost:4001"}
	client := etcd.NewClient(entries)

	client.SyncCluster()

	_, err := client.Set("hello", "world", 0)
	if err != nil {
		log.Fatal(err)
	}
}
```

It should panic at `client.SyncCluster()`. Now I'm probably doing something wrong when launching etcd but `SyncCluster` should handle this gracefully I guess.

**Comment by abronan** [comment]
Tested on different version:

- `v2.0.8`: panic as well but with a different error (`panic: invalid argument to Intn`)
- `v0.4.8`: works fine

I think it's definitely due to the values I give to `--listen-client-urls` and `--advertise-client-urls`. I launch etcd `v2.0.11/v2.0.8` containers specifying those values whereas the `v0.4.8/v0.4.6` containers are launched as is.

**Comment by yichengq** [comment]
@abronan I think the problem is the version of go-etcd. I checkouted the version of go-etcd in swarm, and it did panic, but current master didn't. Could you give current master a try?
Your `--listen-client-urls` and `--advertise-client-urls` settings are totally ok.

**Comment by abronan** [comment]
@yichengq Indeed! Works great with master at least for the panic. I get another error though using `SyncCluster`: `unsupported protocol scheme \"\"`. If I comment it out it works fine. Not sure what's wrong here.

**Comment by abronan** [comment]
I should probably take a look at other repos using `go-etcd` and see if we are doing something wrong.

**Comment by yichengq** [comment]
I think you are in right direction. This error happens when it cannot parse the url, do you have more context?

**Comment by abronan** [comment]
Thanks for your help @yichengq. Actually we are just feeding the call to `NewClient` with the proper urls to connect to an `etcd` instance. Not sure if we are doing anything fancy as I'm watching other examples and it looks like we are doing the same. Without the call to `SyncCluster`, it works fine but I'm unfamiliar with the `SyncCluster` process and what it does under the hood. Seems that it fails at `createHttpPath()`.

We are using a single `etcd` instance for testing purposes, without any other `peers`.

**Comment by yichengq** [comment]
Could you give me the way to reproduce it step by step? And error log line.

**Comment by abronan** [comment]
*Update*: Code works perfectly fine, the error is only happening on the Integration tests that are running on a `docker in docker` setup.

The log line below just in case, this might be tricky to track down:

```
"501: All the given peers are not reachable (failed to propose on members [] twice [last error: Put /v2/keys/test/docker/swarm/nodes/127.0.0.1:5423: unsupported protocol scheme \"\"]) [0]"
```

The `members` list seems to be empty. I launch the container the same way I do on a regular host, specifying the relevant flags. But because of the `docker in docker` setup this time this might be related to `--advertise-client-url` or port expose parameter of `docker run`. I need to inspect the container and see what happens.

I'll close this issue as this was my misunderstanding about `go-etcd` client and `etcd` versions matching. Thanks for the help @yichengq, greatly appreciated!

**Comment by abronan** [comment]
Quick update (can be useful to someone): We were directly trying to use etcd in CI without properly waiting for the store to be available, thus the empty members list after a `SyncCluster`. 

This was working without it because our code logic is to wait for the store to be available but because we were calling `SyncCluster` too soon we were left with an empty members list ;)

A little `sleep 3` after launching the container did the trick.
