### ISSUE TITLE
Improve performance of reading responses from etcd by using ugorji codec

### ISSUE THREAD

**Issue by fgrzadkowski** [coreos/go-etcd#217]
In kubernetes we intensively use etcd go client library to communicate with etcd server. We've noticed that unmarshalling responses from etcd takes significant amount of time. One option to improve performance of this library would be to use [ugorji code](https://github.com/ugorji/go/tree/master/codec) that generates code for (un)marshalling, which is much faster than a regular go codec that uses reflections.

I did initial benchmarks and it gives around ~2 speed up (depending on the size of a Node).

Would this change be considered if I sent it. It should be very short (1 file with generated code, one line change in response.go and some benchmarks).

@davidopp @wojtek-t

**Comment by timothysc** [comment]
+1.
@yichengq, @xiang90 ^ comments?

**Comment by fgrzadkowski** [comment]
Refs https://github.com/GoogleCloudPlatform/kubernetes/issues/4521

**Comment by xiang90** [comment]
SGTM

**Comment by timothysc** [comment]
cc @eparis

**Comment by fgrzadkowski** [comment]
One more thing - this will add a dependency on ugorji codec - both to generate code and for the decoding code (see [example](http://ugorji.net/blog/go-codec-primer#decoding)). How should I solve it? Should I just update README.md and mention that user should also ```go get``` ugorji code?

**Comment by wojtek-t** [comment]
I agree this can help a lot Kubernetes
