### ISSUE TITLE
Is it safe to use one etcd.Client in multiple goroutines?

### ISSUE THREAD

**Issue by unknownzerx** [coreos/go-etcd#221]
I have read but not quite understanding
> go-etcd is not thread-safe, and it may have race when switching member or updating cluster.

Whatever, all I want to do is
```go
go client.Watch(....)
client.Set(...) // or another Watch
```

Is that safe?

**Comment by yichengq** [comment]
We don't have protection around internal cluster struct, so when go-etcd switches members when the remote member is unavailable, it may have race.

**Comment by unknownzerx** [comment]
Understood. Thanks.

**Comment by GeertJohan** [comment]
@yichengq If that is the only problem, would it be possible to add that protection, or is that non-trivial?

**Comment by yichengq** [comment]
@GeertJohan Mainly. It also depends on what guarantee users want to get.
