### ISSUE TITLE
K8s API server hangs with --etcd-config

### ISSUE THREAD

**Issue by mnemotiv** [coreos/go-etcd#223]
If I'm using --etcd-servers=http://127.0.0.1:2379 - API server starts normally.

If I'm using --etcd-config=/var/lib/etcd/etcd.json - API server hangs right after publishing swagger log lines and doesn't publish/bind ports and API server process stays "hanged" here without any errors.

```
{
  "cluster": {
    "leader": "http://127.0.0.1:2379",
    "machines": [
      "http://127.0.0.1:2379"
    ]
  },
  "config": {
    "certFile": "",
    "keyFile": "",
    "caCertFiles": [],
    "timeout": 5,
    "consistency": "STRONG"
  }
}
```

I've tried with all certificate files, https protocol and etcd with https/certs also - same  problem with etcd-config.

CoreOS alpha: 695.0.0 and 709.0.0 (this happens on both versions).
Kubernetes: 0.18.0 , 0.18.1 , 0.18.2

**Comment by yichengq** [comment]
This repo focuses on go-etcd, which is a Go client for etcd.
You may need to open the issue at kubernetes to solve your problem.
