### ISSUE TITLE
panic: codecgen version mismatch: current: 2, need 3. Re-generate file: .../src/github.com/coreos/go-etcd/etcd/response.generated.go

### ISSUE THREAD

**Issue by SpComb** [coreos/go-etcd#240]
$ go get github.com/coreos/go-etcd/etcd
	$ cat > etcd-example.go # from README.md
	$ go run etcd-example.go 
	panic: codecgen version mismatch: current: 2, need 3. Re-generate file: .../src/github.com/coreos/go-etcd/etcd/response.generated.go

	goroutine 1 [running]:
	github.com/coreos/go-etcd/etcd.init·3()
		/.../src/github.com/coreos/go-etcd/etcd/response.generated.go:37 +0x207
	github.com/coreos/go-etcd/etcd.init()
		.../src/github.com/coreos/go-etcd/etcd/watch.go:103 +0x531
	main.init()
		.../etcd-example.go:16 +0x42
	exit status 2

github.com/ugorji/go/codec seems to have had an API/ABI break: https://github.com/ugorji/go/commit/718a1bcd1902bb42e926b0e54f6686879f5a9a79

**Comment by yichengq** [comment]
Fixed by #239
