### ISSUE TITLE
Can not build go-etcd

### ISSUE THREAD

**Issue by shenshouer** [coreos/go-etcd#242]
# github.com/coreos/go-etcd/etcd
    ../../coreos/go-etcd/etcd/response.generated.go:112: r.EncodeMapKVSeparator undefined (type     codec.encDriver has no field or method EncodeMapKVSeparator)
    ../../coreos/go-etcd/etcd/response.generated.go:123: r.EncodeArrayEntrySeparator undefined (type codec.encDriver has no field or method EncodeArrayEntrySeparator)
    ../../coreos/go-etcd/etcd/response.generated.go:137: r.EncodeMapEntrySeparator undefined (type codec.encDriver has no field or method EncodeMapEntrySeparator)
    ../../coreos/go-etcd/etcd/response.generated.go:143: r.EncodeMapKVSeparator undefined (type codec.encDriver has no field or method EncodeMapKVSeparator)
    ../../coreos/go-etcd/etcd/response.generated.go:158: r.EncodeArrayEntrySeparator undefined (type codec.encDriver has no field or method EncodeArrayEntrySeparator)
    ../../coreos/go-etcd/etcd/response.generated.go:173: r.EncodeMapEntrySeparator undefined (type codec.encDriver has no field or method EncodeMapEntrySeparator)
    ../../coreos/go-etcd/etcd/response.generated.go:179: r.EncodeMapKVSeparator undefined (type codec.encDriver has no field or method EncodeMapKVSeparator)
    ../../coreos/go-etcd/etcd/response.generated.go:195: r.EncodeArrayEnd undefined (type codec.encDriver has no field or method EncodeArrayEnd)
    ../../coreos/go-etcd/etcd/response.generated.go:197: r.EncodeMapEnd undefined (type codec.encDriver has no field or method EncodeMapEnd)
    ../../coreos/go-etcd/etcd/response.generated.go:216: r.ReadMapEnd undefined (type codec.decDriver has no field or method ReadMapEnd)
    ../../coreos/go-etcd/etcd/response.generated.go:216: too many errors

**Comment by zstyblik** [comment]
We're having the same problem. Is there any way to fix it?

**Comment by yichengq** [comment]
You could move to https://github.com/coreos/go-etcd/pull/239 for more discussion.

**Comment by zstyblik** [comment]
I can confirm this has been resolved. At least for us. Thank you for a quick fix.
