### ISSUE TITLE
Error with starting etcd - 2.2.4 ( latest version) 

### ISSUE THREAD

**Issue by vandita31** [coreos/go-etcd#249]
HI ,

I'm starting a standalone ETCD instance and pulled the latest version -

[root@cdaetcd-ch2-2p system]# etcd --version
etcd Version: 2.2.4
Git SHA: bdee27b
Go Version: go1.5.3
Go OS/Arch: linux/amd64
[root@cdaetcd-ch2-2p system]# 

However , etcd fails to start and I'm unable to explain much with this error-

[root@cdaetcd-ch2-2p system]# systemctl status etcd
etcd.service - Etcd Server
   Loaded: loaded (/usr/lib/systemd/system/etcd.service; enabled)
   Active: failed (Result: start-limit) since Wed 2016-01-27 21:32:19 UTC; 12min ago
  Process: 20792 ExecStart=/usr/bin/etcd (code=exited, status=1/FAILURE)
 Main PID: 20792 (code=exited, status=1/FAILURE)

Jan 27 21:32:19 cdaetcd-ch2-2p systemd[1]: etcd.service: main process exited, code=exited, status=1/FAILURE
Jan 27 21:32:19 cdaetcd-ch2-2p systemd[1]: Failed to start Etcd Server.
Jan 27 21:32:19 cdaetcd-ch2-2p systemd[1]: Unit etcd.service entered failed state.
Jan 27 21:32:19 cdaetcd-ch2-2p systemd[1]: etcd.service holdoff time over, scheduling restart.
Jan 27 21:32:19 cdaetcd-ch2-2p systemd[1]: Stopping Etcd Server...
Jan 27 21:32:19 cdaetcd-ch2-2p systemd[1]: Starting Etcd Server...
Jan 27 21:32:19 cdaetcd-ch2-2p systemd[1]: etcd.service start request repeated too quickly, refusing to start.
Jan 27 21:32:19 cdaetcd-ch2-2p systemd[1]: Failed to start Etcd Server.
Jan 27 21:32:19 cdaetcd-ch2-2p systemd[1]: Unit etcd.service entered failed state.
[root@cdaetcd-ch2-2p system]# 

I had to set Type=notify and NotifyAccess=all to get rid of some errors over the default config. I set Restart=always but it fails even without that option enabled. Here is what my config looks like -

[root@cdaetcd-ch2-2p system]# cat /usr/lib/systemd/system/etcd.service
[Unit]
Description=Etcd Server
After=network.target

[Service]
Type=notify
WorkingDirectory=/var/lib/etcd/
EnvironmentFile=-/etc/etcd/etcd.conf
User=etcd
ExecStart=/usr/bin/etcd
NotifyAccess=all
Restart=always

[Install]
WantedBy=multi-user.target
[root@cdaetcd-ch2-2p system]# 

Journalctl also doesnt seem to provide me much info.

[root@cdaetcd-ch2-2p system]# journalctl -u etcd.service --since today
-- Logs begin at Mon 2015-06-22 17:07:28 UTC, end at Wed 2016-01-27 21:32:19 UTC. --
Jan 27 21:32:19 cdaetcd-ch2-2p systemd[1]: Starting Etcd Server...
Jan 27 21:32:19 cdaetcd-ch2-2p systemd[1]: etcd.service: main process exited, code=exited, status=1/FAILURE
Jan 27 21:32:19 cdaetcd-ch2-2p systemd[1]: Failed to start Etcd Server.
Jan 27 21:32:19 cdaetcd-ch2-2p systemd[1]: Unit etcd.service entered failed state.
Jan 27 21:32:19 cdaetcd-ch2-2p systemd[1]: etcd.service holdoff time over, scheduling restart.
Jan 27 21:32:19 cdaetcd-ch2-2p systemd[1]: Stopping Etcd Server...
Jan 27 21:32:19 cdaetcd-ch2-2p systemd[1]: Starting Etcd Server...
Jan 27 21:32:19 cdaetcd-ch2-2p systemd[1]: etcd.service start request repeated too quickly, refusing to start.
Jan 27 21:32:19 cdaetcd-ch2-2p systemd[1]: Failed to start Etcd Server.
Jan 27 21:32:19 cdaetcd-ch2-2p systemd[1]: Unit etcd.service entered failed state.
[root@cdaetcd-ch2-2p system]# 

Can anyone provide some assistance as to what is causing the above error for ETCD to fail? And also a possible resolution?

Would love some insight.

Thanks,

Vandita

**Comment by vandita31** [comment]
These are the permissions on the /var/lib/etcd directory - 

[root@cdaetcd-ch2-2p system]# ls -la /var/lib/etcd/
total 8036
drwxr-xr-x   3 etcd etcd      45 Jun 22  2015 .
drwxr-xr-x. 36 root root    4096 Jan 27 03:21 ..
drwx------   3 etcd etcd      19 Jan 27 06:48 automation
-rw-r--r--   1 etcd etcd 8222720 Jun 22  2015 old-cluster.tar
[root@cdaetcd-ch2-2p system]#

**Comment by jonboulle** [comment]
This issue was moved to coreos/etcd#4308
